layout:
  application:
    # - name: facade
    #   source: asset:clientFacade
    #   target: "{{ joinFilePath .Target .ClientPackage }}"
    #   file_name: "{{ .Name }}_client.go"
    # - name: utils
    #   source: "swagger/templates/utils.gtpl"
    #   target: "{{ joinFilePath .Target }}/resources/utils"
    #   file_name: "helper_functions.go"
  models:
    # - name: definition
    #   source: asset:model
    #   target: "{{ joinFilePath .Target .ModelPackage }}"
    #   file_name: "{{ (snakize (pascalize .Name)) }}.go"
    - name: schema
      source: "swagger/templates/schema.gtpl"
      target: "{{ joinFilePath .Target }}/schemas/gen"
      file_name: "{{ camelize .Name }}_schema.go"
    # - name: tf_config
    #   source: "swagger/templates/tf_config.gtpl"
    #   target: "{{ joinFilePath .Target }}/tf_config/gen"
    #   file_name: "{{ camelize .Name }}_schema.tf"
    # - name: datadump
    #   source: "swagger/templates/datadump.gtpl"
    #   target: "{{ joinFilePath .Target }}/data_profile"
    #   file_name: "{{ camelize .Name }}_models.profile"
  operations:
    # - name: parameters
    #   source: asset:clientParameter
    #   target: "{{ joinFilePath .Target .ClientPackage .Package }}/gen"
    #   file_name: "{{ (snakize (pascalize .Name)) }}_parameters.go"
    # - name: responses
    #   source: asset:clientResponse
    #   target: "{{ joinFilePath .Target .ClientPackage .Package }}/gen"
    #   file_name: "{{ (snakize (pascalize .Name)) }}_responses.go"
  operation_groups:
    # - name: client
    #   source: asset:clientClient
    #   target: "{{ joinFilePath .Target .ClientPackage .Name }}/gen"
    #   file_name: "{{ (snakize (pascalize .Name)) }}_client.go"
    # - name: resources
    #   source: "swagger/templates/resources.gtpl"
    #   target: "{{ joinFilePath .Target }}/resources/gen"
    #   file_name: "{{ camelize .Name }}_resource.go"
    # - name: datadump
    #   source: "swagger/templates/datadump.gtpl"
    #   target: "{{ joinFilePath .Target }}/resource_profile"
    #   file_name: "{{ camelize .Name }}_resource.profile"
